### ISSUE TITLE
(gdk): Directories are not cleaned up when the `--name` option is specified but the template does not exist

### ISSUE THREAD

**Issue by timmattison** [aws-greengrass/aws-greengrass-gdk-cli#100]
**Describe the bug**
Directories are not cleaned up when the `--name` option is specified but the template does not exist

**To Reproduce**
Run `gdk component init -l java -t template -n nonexistent`

**Expected behavior**
The directory named `nonexistent` should not be created because the template does not exist.

**Actual behavior**
gdk will first create the directory `nonexistent` before determining that the template does not exist.

**Comment by saranyailla** [comment]
Hi Tim, 
Thanks for trying our CLI tool. I see room for improvement in the customer experience here but we'll need to prioritize and work on it.  However, this can be categorized as an improvement to the customer experience rather than a bug. Let us know what you think.

**Comment by saranyailla** [comment]
Fixed this as part of GDK 1.3.0. With this change, a new directory is created only when a template or repository exists when a project is initiated with `--name` argument. Closing this out.
