### ISSUE TITLE
(gdk): support for retrieving most recent published version number for a component

### ISSUE THREAD

**Issue by t04glovern** [aws-greengrass/aws-greengrass-gdk-cli#105]
**Feature Description**
Add functionality to retrieve a components most recent version with the `gdk`

**Use Case**
I'd like to be able to publish a component with `gdk component publish` and then retrieve the most recent version number with a CLI command for use when chaining a component publish with a GreengrassV2 deployment. As I'd need a way to extract the new version number that I can insert into the deployment.json/yaml.

**Proposed Solution**
Something along the lines of `gdk component version` to output `1.0.10` for example, if the most recent published version is `1.0.10`.

```json
        "com.blah.blah": {
            "componentVersion": "1.0.9", <--- Need a way to retrieve the version for changing my deployment.
            "runWith": {}
        },
```

Alternatively, if the output of `gdk component publish` could be output as json and a `--query` parameter used to get the version, that would suffice

**Other**
I suspect there might be some confusion if someone runs `gdk component version` prior to publishing local changes, so perhaps there's a different way I could approach this problem (possibly using the `aws` cli instead).

**Comment by saranyailla** [comment]
Hi Nathan, 
Thanks for using the gdk cli tool. 
- I definitely see value in knowing the latest version of the component published using gdk `publish` command as opposed to fetching the latest version of _any_ component with a different command using `gdk` as one can achieve the same using `awscli`. 
- As of the current status of the tool, we'll have to parse the gdk publish command text output and look for specific log that says `[2022-05-02 09:20:16] INFO - Created private version 'a.b.c' of the component in the account.'<component-name>'.` to get the latest version of the component published. 

But, as you mentioned here, producing the gdk command output as a json file would be a better approach (similar to what `awscli` does) as we can include multiple pieces of useful information.

However, at this time, we will have to look into more and prioritize accordingly.

**Comment by t04glovern** [comment]
No worries! for now I've gotten around this by using the following with the awscli, posting here in case others run into a requirement

```bash
aws greengrassv2 list-component-versions \
  --output text \
  --no-paginate \
  --arn arn:aws:greengrass:${AWS_REGION}:${AWS_ACCOUNT_ID}:components:com.blah.blah \
  --query 'componentVersions[0].componentVersion'
```
