### ISSUE TITLE
(gdk): ca-central-1 not supported

### ISSUE THREAD

**Issue by gearoid-moore** [aws-greengrass/aws-greengrass-gdk-cli#132]
**Feature Description**
Making a feature request based off this RePost suggestion:
https://repost.aws/questions/QUe_mJGGF6ScSvyoj0uLixLQ/aws-io-t-pub-sub-sdk-workshop-gdk-tool-fails-in-ca-central-1

I am not the repost thread creator, just someone with the same issue. 
**Use Case**
I used gdk-cli in a publishing pipeline that needs to publish to the canada region.

**Proposed Solution**
As suggested in repost - add ca-central-1 to the schema.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by Nelsonochoam** [comment]
Hey @gearoid-moore,

Thanks for reaching out and bringing this up. We are working on getting this fixed and will be available on our next patch release 1.2.1 which should be completed in the next couple of days.

Cheers,

Nelson

**Comment by Nelsonochoam** [comment]
@gearoid-moore we just released v1.2.1 which will accept the `ca-central-1` region. Closing this issue
