### ISSUE TITLE
(gdk): S3 bucket creation fails if account is on bucket limit

### ISSUE THREAD

**Issue by gearoid-moore** [aws-greengrass/aws-greengrass-gdk-cli#138]
**Describe the bug**
It seems like the s3 bucket creation exception handling needs tweaking, exception catch for bucket limit supersedes situation where bucket exists and at limit. 

**To Reproduce**
Create an account with the limit of S3 buckets. Try to publish a component to a bucket that already exists ( meaning no new buckets should be created ) . It will fail with an error that it cannot create a bucket. 

**Expected behavior**
Using the full bucket quota is a valid behaviour and should be supported. 

**Actual behavior**
Component does not publish . 

**Environment**
 - OS:  Ubuntu 20.04
 - Nucleus version: 2.9.3

**Additional context**
Cannot publish components using gdk as I am maxed out on buckets.

**Comment by saranyailla** [comment]
This is fixed in GDK v1.2.2.
