### ISSUE TITLE
(gdk): Small typo in zip build, should be "exclude", not "excludes"

### ISSUE THREAD

**Issue by jfduque** [aws-greengrass/aws-greengrass-gdk-cli#140]
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/5f320f60e3a9b7050d0b4ab472b62df815cad5f0/gdk/build_system/Zip.py#L91

The docs uses [exclude](https://docs.aws.amazon.com/greengrass/v2/developerguide/gdk-cli-configuration-file.html#gdk-config-examples). 

Tested with the following gdk-config.json

```json
{
  "component": {
    "com.example.Component": {
      "author": "John Doe <jdoe@example.com>",
      "version": "NEXT_PATCH",
      "build": {
        "build_system": "zip",
        "options": {
          "exclude": [".git", "venv"]
        }
      },
      "publish": {
        "bucket": "example",
        "region": "us-east-1"
      }
    }
  },
  "gdk_version": "1.2.0"
}

```

**Comment by Nelsonochoam** [comment]
@jfduque thanks for catching this. This was a miss on the documentation from our end, we are working on updating the documentation and will have it changed today. It should have been `excludes` instead of `exclude`
