### ISSUE TITLE
(gdk): Recipe parsing is case sensitive

### ISSUE THREAD

**Issue by gregbreen** [aws-greengrass/aws-greengrass-gdk-cli#142]
**Describe the bug**
GDK is particular about case within a recipe. Specifically in regards to `Uri` versus `URI` as reported by a customer here: https://repost.aws/questions/QUCjUlboSFRzaa-X22FOrcPA/an-error-occurred-validation-exception-when-calling-the-create-component-version-operation. The AWS CLI accepts `Uri`, GDK does not. Problem confirmed in both GDK 1.21 and 1.1.0.

**To Reproduce**
Following our tutorial as written: https://docs.aws.amazon.com/greengrass/v2/developerguide/defer-component-updates-tutorial.html. The recipe has `Uri` rather than `URI`.

**Expected behavior**
Component version should be published.

**Actual behavior**
Publish fails.

**Environment**
 - OS: Ubuntu 20.04
 - JDK version: N/A
 - Nucleus version: N/A

**Comment by saranyailla** [comment]
This is fixed in GDK v1.2.2.
