### ISSUE TITLE
Zip file exclude file names that starts with test

### ISSUE THREAD

**Issue by cbenitez81** [aws-greengrass/aws-greengrass-gdk-cli#143]
Refer to https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/ba77abcd5c92dd222fa62ab957587d7edf5599d6/gdk/build_system/Zip.py#L84

```
if not options:
            ignore_list.extend([
                "test*",
                ".*",
                "node_modules",
            ])
        else:
            ignore_list.extend(options.get("excludes", []))
```

If a file starts with test, it gets excluded for the zipping. Many libraries have files that starts with that name, eg pandas and if we were to include the library as part of the component the program will fail. I think that this needs to be removed of clarified in the documentation

**Comment by saranyailla** [comment]
Hi,
Thank you for reporting this issue. If you don't want gdk to exclude `test*` folders, please use `excludes` key under `options` entry of `build` in the `gdk-config.json` file to exclude the files you want to exclude from being zipped. 
If you don't specify this, gdk excludes `test*` by default.

This new feature is added from 1.2.0 onwards. More info in the [docs](https://docs.aws.amazon.com/greengrass/v2/developerguide/gdk-cli-configuration-file.html#gdk-config-format). 

```
      "build": {
        "build_system" : "zip",
        "options": {
           "excludes": [".*", "node_modules"]
        }
      }
```

**Comment by cbenitez81** [comment]
I see the documentation but I don't see where is specified that `test*` is set by default, just in the code. Probably this needs to be more front and center or just leave these `[".*", "node_modules"]` by default.

**Comment by cbenitez81** [comment]
I think that the proposed solutions does not work, I'm getting this error `Project configuration file 'gdk-config.json' is invalid. Please correct its format and try again. Error: Additional properties are not allowed ('excludes' was unexpected)` . My guess is that the schema in https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/5f320f60e3a9b7050d0b4ab472b62df815cad5f0/gdk/static/config_schema.json#L83 has typo and it should be "excludes" instead of "exclude"

**Comment by saranyailla** [comment]
This is fixed in GDK v1.2.2.

**Comment by cbenitez81** [comment]
I still think  that `test`  should not be included in the list by default. I have several projects that requires creating a virtual environment as part of the component that has pandas.testing, torch.testing, etc. The component breaks on arrival, it's a relatively obscure problem to figure it out. Any plans of fixing this issue?

**Comment by MikeDombo** [comment]
Hi @cbenitez81,

The pattern `test*` only excludes files which begin with test, not files with test somewhere in the name. https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/main/gdk/build_system/Zip.py#L97.

Are you using GDK v1.4.0 and it is excluding files with test somewhere in the name?

**Comment by cbenitez81** [comment]
I  meant those as examples, but just doing `import torch` will fail if the test package is not there, or `import pandas as pd` even as a subfolder of the environment. The suffix test is quite popular and I've seen this case for other libraries. I know that as part of the install configuration you can potentially do pip or create the environment on the spot but some projects have no reliable internet connectivity or block sites besides AWS

**Comment by MikeDombo** [comment]
I did reproduce the issue.

**Comment by patrzhan** [comment]
Pull request https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/253 fixes this issue by only excluding files from the root directory. Will be included in the next patch release, will keep this thread updated.

**Comment by patrzhan** [comment]
GDK version 1.5.0 has been released and allows using full globs that can specify directory if desired, so projects that need to exclude from just the root directory can do so now. https://github.com/aws-greengrass/aws-greengrass-gdk-cli/releases/tag/v1.5.0
