### ISSUE TITLE
(gdk): gdk_version key in gdk-config file is 1.0.0, with gdk 1.2.1

### ISSUE THREAD

**Issue by gearoid-moore** [aws-greengrass/aws-greengrass-gdk-cli#145]
**Describe the bug**
gdk_version key does not show the version of gdk used to create the app.

**To Reproduce**
Create a component using the HelloWorld template:
`gdk component init -n VersionName -l python -t HelloWorld`

Buggy behaviour is observed for both python and java HelloWorld templates.

**Expected behavior**
gdk_version is 1.2.1

**Actual behavior**
gdk_version is 1.0.0

**Environment**
 - OS: 20.04.1-Ubunt
 - JDK version: openjdk 11.0.18 2023-01-17
 

E.g. what is the impact of the bug?
Low impact, but still represents broken behaviour.

**Comment by saranyailla** [comment]
Hi,
The `gdk_version` in the `gdk-config.json` file is used to specify the minimum version of the GDK CLI that is compatible with the component. 
All of the existing templates are compatible with GDK v1.0.0 and above. So, you see [`gdk_version": "1.0.0`](https://github.com/aws-greengrass/aws-greengrass-component-templates/blob/main/templates/python/HelloWorld/gdk-config.json#L15) in the component templates.
