### ISSUE TITLE
On Windows ./ is not valid

### ISSUE THREAD

**Issue by 1-alex98** [aws-greengrass/aws-greengrass-gdk-cli#273]
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/cfd3e1078b4bfdaec27f09e29ab33d7343981bd1/gdk/build_system/GradleWrapper.py#L12

**Comment by MikeDombo** [comment]
Thank you for letting us know about this.

This is fixed by #274.

It may take us a little while before it is released fully, but you can use the updated version immediately by running `pip3 install git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git@development --upgrade`

**Comment by MikeDombo** [comment]
Resolved in 1.6.2.

Thank you
