### ISSUE TITLE
Problem installing newest version

### ISSUE THREAD

**Issue by martinmecir-gymbeam** [aws-greengrass/aws-greengrass-gdk-cli#284]
Hey, i'm getting this error while installing latest version of gdk-cli
<img width="1062" alt="Screenshot 2024-03-21 at 15 00 15" src="https://github.com/aws-greengrass/aws-greengrass-gdk-cli/assets/164362546/8aea8258-37a6-4201-94cf-c61137446997">

Any idea how to fix this?

**Environment**
 - OS: Linux raspberrypi 4.19.88-v7+ #1284 SMP Wed Dec 11 13:46:41 GMT 2019 armv7l GNU/Linux
 - JDK version: openjdk version "1.8.0_332"
 - Python: 3.5.3
 - pip:  9.0.1

**Comment by MikeDombo** [comment]
Hello there,
Your python version is 3.5 which is end of life as of 2020. Please use a newer Python version, at least 3.7

**Comment by martinmecir-gymbeam** [comment]
Thank you sir, i'll go ahead and close this issue
