### ISSUE TITLE
Passing Path object to shutils.move in gdk component init

### ISSUE THREAD

**Issue by sgreen-GC** [aws-greengrass/aws-greengrass-gdk-cli#33]
Hi,

Just been checking the GDK out and I came up against a problem when init'ing a new python component from the HelloWorld template.
See below for reproduction and error:
```
>gdk component init -l python -t HelloWorld
[2021-11-30 12:28:07] INFO - Initializing the project directory with a python component template - 'HelloWorld'.
[2021-11-30 12:28:07] INFO - Fetching the component template 'HelloWorld-python' from Greengrass Software Catalog.

=============================== ERROR ===============================
Could not initialize the project with component template 'HelloWorld'.
'WindowsPath' object has no attribute 'rstrip'
```

I had a look around and it looks like its a problem with passing a Path object to the shutil.move() function:
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/7750b60dcc2714264f8f6a99c720b055f6eb7bfd/gdk/commands/component/init.py#L110

I changed it to convert the Path to a string and it seemed to work.

I was running on Windows 10, using GDK v1.0.0, in a python3.8.2 virtualenv.
I also tried it on Ubuntu 20.04, under WSL2, and got a similar error:
```
'PosixPath' object has no attribute 'rstrip'
```

Let me know if there's any other detail I can provide.

**Comment by pelder-lumenix** [comment]
Similar problem on Ubuntu 20.04. Tried with python 3.6, 3.7 and 3.8. Likely cause is the assumption that `shutil.move` accepts Path objects. According to [this StackOverflow](https://stackoverflow.com/questions/61327385/trying-to-use-on-path-object-python), it does not. The fix appears to be as simple as:

```
shutil.move(str(f), str(utils.current_directory))
```

**Comment by pallavi03** [comment]
Thanks @sgreen-GC & @pelder-lumenix  for pointing this out. We are waiting for [PR](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/35) authored by Paul to be ready for merging.

**Comment by pelder-lumenix** [comment]
@pallavi03 : The test failure is related to changed arguments passed to the test's mock of `shutil.move`. But, before I change the test, let's take a more detailed look at the failure.

* the message received is that a Path object (either PosixPath or WindowsPath) does not have an `rstrip()` method.
* in the Python 3.6 shutil implementation, there is exactly one call to `rstrip()` in `_basename()`. See [code](https://github.com/python/cpython/blob/2c56c97f015a7ea81719615ddcf3c745fba5b4f3/Lib/shutil.py#L510).
* In turn, `_basename()` is only called from `shutil.move()` on the 'src' (1st) argument. See [code](https://github.com/python/cpython/blob/2c56c97f015a7ea81719615ddcf3c745fba5b4f3/Lib/shutil.py#L546).
* Thus, a minimal fix would be to ensure that the first argument is a string.

Doing so let's me run the builds cleanly, so I'll post an update pull request shortly.

In the meantime, you should give some thought to why the tests did not uncover the original failure. The mocking of `shutil.move` means the failing test would never uncover the failure. Perhaps there is a need for another test that actually runs the full code without mocking.

Updated pull request coming in a minute or two.

**Comment by pallavi03** [comment]
@pelder-lumenix I agree. We are working on adding such test.
