### ISSUE TITLE
(gdk component build): build fails when using gradle

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-gdk-cli#73]
**Describe the bug**
I am trying to build my component that uses gradle build system. Build process is successful in IntelliJ IDEA and when using `./gradlew build` from command line but fails when using `gdk component build`

**To Reproduce**
Steps to reproduce the behavior. If possible, provide a minimal amount of code that causes the bug.

Run `gdk component build` 

**Expected behavior**

Successful build

**Actual behavior**
Tell us what actually happened.

```
* Where:
Build file '/Users/angmas/Projects/aws-greengrass-labs-secretsmanagerclient/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'community.greengrass.SecretsManagerClient'.
> Could not find method testCompile() for arguments [com.github.stefanbirkner:system-rules:1.19.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Environment**
 - OS: [e.g. Ubuntu 20.04] (If possible, provide output of `uname -a`) 
 - JDK version:
 - Nucleus version:

**Additional context**

E.g. what is the impact of the bug?

**Comment by pallavi03** [comment]
@massi-ang  can you confirm if the issue persist?

**Comment by massi-ang** [comment]
Same issue:
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xxxx/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'community.greengrass.SecretsManagerClient'.
> Could not find method testCompile() for arguments [com.github.stefanbirkner:system-rules:1.19.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
[2022-02-24 08:46:33] INFO - Copying over the build artifacts to the greengrass component artifacts build folder.
[2022-02-24 08:46:33] INFO - Updating artifact URIs in the recipe.
[2022-02-24 08:46:33] INFO - Creating component recipe in '/Users/xxx/recipes'.
```

The same happens if I do `gradle build` from the shell

**Comment by massi-ang** [comment]
I resorted to use a custom build command, but in order to copy the artifact in the right folder I need to know the version of the component in my build script. Is `gdk` setting an environment variable with the version number in the process that runs the build script?

**Comment by saranyailla** [comment]
> The same happens if I do `gradle build` from the shell

Gdk runs `gradle build`  on behalf of you. So, it needs to be fixed first for GDK to properly build the component. 



> I resorted to use a custom build command, but in order to copy the artifact in the right folder I need to know the version of the component in my build script. Is `gdk` setting an environment variable with the version number in the process that runs the build script

`gdk component build` command uses the exact versions specified in the gdk-config.json. (Only `publish` command calculates the component version)

For eg. It'd be `greengrass-build/component_name/NEXT_PATCH`  folder for artifacts if `NEXT_PATCH` is the version in `gdk-config.json` file.
