### ISSUE TITLE
(gdk): automatic generation of artifacts URIs when using custom build scripts

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-gdk-cli#81]
**Feature Description**
When using custom build scripts, the scripts must copy the recipe.yaml in the `greengrass-build/recipes` folder, and update the artifacts URI to the s3 path corresponding to the bucket set in gdk-json. 

The gdk should provide a setting to allow such process to be executed by the gdk tool even when using a custom build script.

**Use Case**
To be able to use custom build scripts

**Proposed Solution**
GDK should always take the `recipe.yaml` and replace the artifact URI with the correct value and copy the file in `greengrass-build`

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by saranyailla** [comment]
Hi Massi,

- GDK builds artifacts and recipe in a certain way when default options like maven, gradle and zip are chosen for build system in the config file.  With our default build systems, gdk knows where to find the built artifacts. If `custom` option is chosen, we have no idea where to look for the artifacts. So, we need customers to put them inside`greengrass-build`.

- The intent behind using custom build command is to customize the way **_both artifacts and recipes_** of a component are built without being restricted by gdk in anyway. It's absolutely flexible where gdk doesn't do partial building of them. 
For eg. If the source code of a component produces an arn which needs to be updated in the recipe configuration during the build, customers can update the recipe as needed before gdk uses it to publish the component. 


For the comment on updating the s3 artifact URIs in build, it is done only in the `publish` command. It's the same behavior for both the default and custom build systems. We update the s3 URIs in only publish command for both the build systems.

**Comment by massi-ang** [comment]
Thanks for the clarification. 

Regarding the custom build, say I specify the Artifact path in the recipe as `s3://abc.zip`, where should my custom build script put the `abc.zip` file for gdk to find it? What would be the resulting S3 key of the uploaded object?

**Comment by saranyailla** [comment]
> Thanks for the clarification.
> 
> Regarding the custom build, say I specify the Artifact path in the recipe as `s3://abc.zip`, where should my custom build script put the `abc.zip` file for gdk to find it? What would be the resulting S3 key of the uploaded object?

- The artifact `abc.zip` must go into `greengrass-build/artifacts/component-name/component-version/` directory where `component-name` and `component-version` are the ones specified in the `gdk-config.json` file. Eg. if component name is ABC and component version is NEXT_PATCH in the config file, you need to copy the artifacts to `greengrass-build/artifacts/ABC/NEXT_PATCH/` directory. 
- The recipe `recipe.yaml` must go into `greengrass-build/recipes/` directory. 
- The resulting s3 URI of the artifact will be `s3://bucket-name/component-name/component-version/abc.zip` where `bucket-name` is formed from bucket-prefix from the gdk-config file appended with region and account number.

**Comment by saranyailla** [comment]
Hi Massi,
Closing the issue. Please reopen if there are more questions or concerns related to this. 

Thanks!
