### ISSUE TITLE
(gdk): use `./gradlew` instead of `gradle` to build components

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-gdk-cli#84]
**Feature Description**
When using gradle a `gradlew` file is normally present in the root folder of the project and takes care of downloading the correct version of gradle compatible with the build file. Using `gradle` as currently done has 2 main disadvantages:
1. requires `gradle` to be installed system wide, which might not be the case
2. the system wide `gradle` version might be incompatible with `gradle.build`

**Use Case**
Have a more consistent way of building `gradle` projects

**Proposed Solution**
use `./gradlew`, if present, to build component specifying `gradle` as build system. Fallback to `gradle` if `./gradlew` is not found.

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by massi-ang** [comment]
Relates to #73

**Comment by saranyailla** [comment]
Hi Massi, thanks for the suggestion. I'll research more about this solution to prioritize and work on it accordingly.
