### ISSUE TITLE
(gdk): support for overriding `gdk-config.json` properties at runtime

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-gdk-cli#86]
**Feature Description**
To make the `gdk-config.json` more portable it could be useful to be able to override default values of some properties, such as buckets, through env variable or cli flags

**Use Case**
Why do you need this feature?
When testing my component I need to specify a bucket value, but I do not want this value to be committed in git. Currently, I have to replace the value with a placeholder every time I need to do a commit

**Proposed Solution**
Support overriding the values of some properties by using flags or environment variables.

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by gearoid-moore** [comment]
Another example of this would be to specify the region value. 

If you are deploying your greengrass components on multiple stacks, you are limited by the hard-coding of the publish['region'] key. Makes it very difficult to run a pipeline that deploys across multiple stacks.

**Comment by MikeDombo** [comment]
Implemented in v1.2.0
