### ISSUE TITLE
(gdk): gdk README leaves out gdk-config.json information

### ISSUE THREAD

**Issue by timmattison** [aws-greengrass/aws-greengrass-gdk-cli#93]
**Describe the bug**
Step 3.2 in the README for gdk will fail if the user hasn't made changes to `gdk-config.json`. There should be a callout here to let the user know that they'll need to do this before they run the command and it fails. That callout should either directly describe the changes they need to make or link to a resource that does.

**To Reproduce**
Try to run step 3.1 and then run step 3.2. You will receive an error message.

**Expected behavior**
The documentation should call out that this needs to be configured before the user gets to step 3.2 and how to do that configuration. The error message should also link to that documentation.

**Actual behavior**
An error message.

**Additional context**
This probably qualifies as a paper cut but definitely slows someone down the first time they try to use GDK.

**Comment by saranyailla** [comment]
Hi Tim, 
Thanks for reporting. We agree that the step to update gdk-config file before running build command has to be added to the README for better customer experience. 

Also, the dedicated section we've in  AWS IoT Greengrass public documentation  for [GDK](https://docs.aws.amazon.com/greengrass/v2/developerguide/create-components.html#create-component-gdk-cli) needs to be properly linked through the GitHub repository.

**Comment by devnaruka** [comment]
PR #102 has been merged into development branch. This will flow to master branch in next release cycle.
