### ISSUE TITLE
(gdk-cli): Default build and update of recipe.yaml do not generate the correct Artifact URI

### ISSUE THREAD

**Issue by abest0** [aws-greengrass/aws-greengrass-gdk-cli#94]
**Describe the bug**
Incorrect Artifact URI written to `{build_folder}/recipes/recipe.yaml` recipe file. The URI written is in an unresolved template format when it should be fully resolved. This defect is in the `is_artifact_in_build` method of the [`BuildCommand`](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/main/gdk/commands/component/BuildCommand.py)

**To Reproduce**

While you can take the time to reproduce this if you'd like, it's pretty evident from the [code](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/60a002f0f2fee84b79022662ba0cae9e0246b6f8/gdk/commands/component/BuildCommand.py#L346) where the error is.

As can be seen below, on part of the `artifact_uri` is formatted with a variable:
`        artifact_uri = f"{utils.s3_prefix}BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION"`

Steps to reproduce:
- `gdk componenent init -l python -t HelloWorld -n HelloTest`
- Update `recipe.yaml`
  - Update `ComponentName` -> **HelloTest**
  - Update `Manifest.Artifacts.URI` -> a valid s3 uri i.e. `s3://some-bucket/HelloTest/0.0.1/HelloTest.zip`
- `gdk component build`

**Expected behavior**
Resolve `BUCKET_NAME`, `COMPONENT_NAME`, `COMPONENT_VERSION`. I'd recommend a simple utility function here where the **bucket**, **component values**, and **artifact zip name** could be specified as parameters. From a quick inspection of the code, there is IMO too much indirection with utility functions dependent on globalish utility functions like [`get_project_config_values()`](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/d42138af965712729f5d67325399a5c91c1a8c59/gdk/commands/component/project_utils.py#L97).

**Actual behavior**
The following is generated in the `greengrass-build/recipes/recipe.yaml` file.

``` 
# greengrass-build/recipes/recipe.yaml
...
ComponentVersion: NEXT_PATCH
Manifests:
- Artifacts:
  - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/MyComponent.zip
    Unarchive: ZIP
  Lifecycle:
  ...
```

**Environment**
 - OS: Amazon Linux 2 x86_64

With this bug, the default build is effectively broken.

**Comment by saranyailla** [comment]
Hi, this is similar to the issue cut here - https://github.com/aws-greengrass/aws-greengrass-gdk-cli/issues/52. 

> Hi, 
Artifacts URIs in the component recipe are updated with `gdk component publish` command only. The updated recipe with S3 artifact URIs is found under `greengrass-build/recipes` as `<component-name>-<component-version>.yaml` recipe file after the publish command is run. 
So, the behavior you're seeing with `gdk component build` command is expected.

Please feel free to reopen this issue if you have more concerns.
